backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# Cela permet de tester localement sans être branché au vrai serveur de prod Github
local_backend: true

media_folder: "public/images/uploads" # Media files will be stored in the repo under public/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Articles de Blog" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.json
    extension: "json"
    format: "json"
    fields: # The fields for each document, usually in front matter
      - {label: "ID (Gardez-le unique, ex: 4)", name: "id", widget: "number", default: 4}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Catégorie", name: "category", widget: "select", options: ["culture", "technologie", "apprentissage"]}
      - {label: "Date de publication", name: "date", widget: "string", hint: "Ex: 10 Avril 2026"}
      - {label: "Auteur", name: "author", widget: "string"}
      - {label: "Rôle de l'auteur", name: "authorRole", widget: "string", required: false}
      - {label: "Image de couverture (URL ou fichier)", name: "image", widget: "image"}
      - {label: "Extrait (Résumé rapide)", name: "excerpt", widget: "text"}
      - {label: "Biographie de l'auteur", name: "authorBio", widget: "text", required: false}
      - {label: "Contenu (Texte intégral de l'article)", name: "body", widget: "markdown"}
